@BookStore_Base_Url = https://localhost:7162

### List all books

GET {{BookStore_Base_Url}}/books
Accept: application/json

### Add a new book

POST {{BookStore_Base_Url}}/books
Accept: application/json
Content-Type: application/json

{
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

### Get the book by ID

@BookID=0193ca6e-eb6c-7a87-9b8d-f6b0a3e9f72f
GET {{BookStore_Base_Url}}/books/{{BookID}}
Accept: application/json

### Update book price

POST {{BookStore_Base_Url}}/books/{{BookID}}/pricehistory
Accept: application/json
Content-Type: application/json

{
  "newPrice": 19.99
}

### Delete the book

DELETE {{BookStore_Base_Url}}/books/{{BookID}}
Accept: application/json

### Add a new user

POST {{BookStore_Base_Url}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "farhan.devx@gmail.com",
  "password": "Pass@word1",
  "fullName": "Farhan Ali"
}

### Login

POST {{BookStore_Base_Url}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "farhan.devx@gmail.com",
  "password": "Pass@word1"
}


### List items in the cart
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzQ0NzE2MjAsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImZhcmhhbi5kZXZ4QGdtYWlsLmNvbSIsImV4cCI6MTczNDQ3NTIyMCwibmJmIjoxNzM0NDcxNjIwfQ.cul-s2ji2czS1ybW9oQr-Uvy-vu8e7yLe0YkRd0N3T4

GET {{BookStore_Base_Url}}/cart
Accept: application/json
Authorization: Bearer {{token}}

### Add item to cart

POST {{BookStore_Base_Url}}/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId": "{{BookID}}",
  "quantity": 1
}

